/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mythrift_constants.h"



const mythriftConstants g_mythrift_constants;

mythriftConstants::mythriftConstants() {
}



