/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mythrift_CONSTANTS_H
#define mythrift_CONSTANTS_H

#include "mythrift_types.h"



class mythriftConstants {
 public:
  mythriftConstants();

};

extern const mythriftConstants g_mythrift_constants;



#endif
