// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "passwordLock.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class passwordLockHandler : virtual public passwordLockIf {
 public:
  passwordLockHandler() {
    // Your initialization goes here
  }

  void connectServer(std::string& _return, const std::string& strDevCode) {
    // Your implementation goes here
    printf("connectServer\n");
  }

  void disconnectServer(const std::string& Session) {
    // Your implementation goes here
    printf("disconnectServer\n");
  }

  void keepAlive(const std::string& Session) {
    // Your implementation goes here
    printf("keepAlive\n");
  }

  void inputPasswd(const std::string& Session, const int32_t iLockType, const std::string& strPassword) {
    // Your implementation goes here
    printf("inputPasswd\n");
  }

  void ResetPasswd(const std::string& strDevCode, const int32_t iLockType, const std::string& strPassword) {
    // Your implementation goes here
    printf("ResetPasswd\n");
  }

  void modifyPasswd(const std::string& strOldPasswd, const std::string& strNewPasswd, const int32_t iLockType) {
    // Your implementation goes here
    printf("modifyPasswd\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<passwordLockHandler> handler(new passwordLockHandler());
  shared_ptr<TProcessor> processor(new passwordLockProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

