/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

/// <summary>
/// 错误类型
/// </summary>
public enum AirExceptionType
{
  PASSWD_EXCEPTION = 0,
  USER_DIONLINE = 1,
}
