/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

public partial class passwordLock {
  public interface Iface {
    /// <summary>
    /// 连接服务器,返回Session
    /// </summary>
    /// <param name="strDevCode">设备编码(加密)</param>
    string connectServer(string strDevCode);
    #if SILVERLIGHT
    IAsyncResult Begin_connectServer(AsyncCallback callback, object state, string strDevCode);
    string End_connectServer(IAsyncResult asyncResult);
    #endif
    /// <summary>
    /// 与服务器断开连接
    /// </summary>
    /// <param name="Session">用户Session</param>
    void disconnectServer(string Session);
    #if SILVERLIGHT
    IAsyncResult Begin_disconnectServer(AsyncCallback callback, object state, string Session);
    void End_disconnectServer(IAsyncResult asyncResult);
    #endif
    /// <summary>
    /// 保活
    /// </summary>
    /// <param name="Session">用户Session</param>
    void keepAlive(string Session);
    #if SILVERLIGHT
    IAsyncResult Begin_keepAlive(AsyncCallback callback, object state, string Session);
    void End_keepAlive(IAsyncResult asyncResult);
    #endif
    /// <summary>
    /// 输入密码
    /// </summary>
    /// <param name="Session">用户Session</param>
    /// <param name="iLockType">锁类型</param>
    /// <param name="strPassword">密码</param>
    void inputPasswd(string Session, int iLockType, string strPassword);
    #if SILVERLIGHT
    IAsyncResult Begin_inputPasswd(AsyncCallback callback, object state, string Session, int iLockType, string strPassword);
    void End_inputPasswd(IAsyncResult asyncResult);
    #endif
    /// <summary>
    /// 重置密码
    /// </summary>
    /// <param name="strDevCode">加密后的设备编码：使得只有某些指定设备才可以进行重置密码，防止黑客通过抓包得到接口并直接调用接口</param>
    /// <param name="iLockType">锁类型</param>
    /// <param name="strPassword">密码</param>
    void ResetPasswd(string strDevCode, int iLockType, string strPassword);
    #if SILVERLIGHT
    IAsyncResult Begin_ResetPasswd(AsyncCallback callback, object state, string strDevCode, int iLockType, string strPassword);
    void End_ResetPasswd(IAsyncResult asyncResult);
    #endif
    /// <summary>
    /// 修改密码
    /// </summary>
    /// <param name="strOldPasswd"></param>
    /// <param name="strNewPasswd"></param>
    /// <param name="iLockType">锁类型</param>
    void modifyPasswd(string strOldPasswd, string strNewPasswd, int iLockType);
    #if SILVERLIGHT
    IAsyncResult Begin_modifyPasswd(AsyncCallback callback, object state, string strOldPasswd, string strNewPasswd, int iLockType);
    void End_modifyPasswd(IAsyncResult asyncResult);
    #endif
  }

  public class Client : IDisposable, Iface {
    public Client(TProtocol prot) : this(prot, prot)
    {
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;
    protected int seqid_;

    public TProtocol InputProtocol
    {
      get { return iprot_; }
    }
    public TProtocol OutputProtocol
    {
      get { return oprot_; }
    }


    #region " IDisposable Support "
    private bool _IsDisposed;

    // IDisposable
    public void Dispose()
    {
      Dispose(true);
    }
    

    protected virtual void Dispose(bool disposing)
    {
      if (!_IsDisposed)
      {
        if (disposing)
        {
          if (iprot_ != null)
          {
            ((IDisposable)iprot_).Dispose();
          }
          if (oprot_ != null)
          {
            ((IDisposable)oprot_).Dispose();
          }
        }
      }
      _IsDisposed = true;
    }
    #endregion


    
    #if SILVERLIGHT
    public IAsyncResult Begin_connectServer(AsyncCallback callback, object state, string strDevCode)
    {
      return send_connectServer(callback, state, strDevCode);
    }

    public string End_connectServer(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_connectServer();
    }

    #endif

    /// <summary>
    /// 连接服务器,返回Session
    /// </summary>
    /// <param name="strDevCode">设备编码(加密)</param>
    public string connectServer(string strDevCode)
    {
      #if !SILVERLIGHT
      send_connectServer(strDevCode);
      return recv_connectServer();

      #else
      var asyncResult = Begin_connectServer(null, null, strDevCode);
      return End_connectServer(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_connectServer(AsyncCallback callback, object state, string strDevCode)
    #else
    public void send_connectServer(string strDevCode)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("connectServer", TMessageType.Call, seqid_));
      connectServer_args args = new connectServer_args();
      args.StrDevCode = strDevCode;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public string recv_connectServer()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      connectServer_result result = new connectServer_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      if (result.__isset.ex) {
        throw result.Ex;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "connectServer failed: unknown result");
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_disconnectServer(AsyncCallback callback, object state, string Session)
    {
      return send_disconnectServer(callback, state, Session);
    }

    public void End_disconnectServer(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      recv_disconnectServer();
    }

    #endif

    /// <summary>
    /// 与服务器断开连接
    /// </summary>
    /// <param name="Session">用户Session</param>
    public void disconnectServer(string Session)
    {
      #if !SILVERLIGHT
      send_disconnectServer(Session);
      recv_disconnectServer();

      #else
      var asyncResult = Begin_disconnectServer(null, null, Session);
      End_disconnectServer(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_disconnectServer(AsyncCallback callback, object state, string Session)
    #else
    public void send_disconnectServer(string Session)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("disconnectServer", TMessageType.Call, seqid_));
      disconnectServer_args args = new disconnectServer_args();
      args.Session = Session;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public void recv_disconnectServer()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      disconnectServer_result result = new disconnectServer_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.ex) {
        throw result.Ex;
      }
      return;
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_keepAlive(AsyncCallback callback, object state, string Session)
    {
      return send_keepAlive(callback, state, Session);
    }

    public void End_keepAlive(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      recv_keepAlive();
    }

    #endif

    /// <summary>
    /// 保活
    /// </summary>
    /// <param name="Session">用户Session</param>
    public void keepAlive(string Session)
    {
      #if !SILVERLIGHT
      send_keepAlive(Session);
      recv_keepAlive();

      #else
      var asyncResult = Begin_keepAlive(null, null, Session);
      End_keepAlive(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_keepAlive(AsyncCallback callback, object state, string Session)
    #else
    public void send_keepAlive(string Session)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("keepAlive", TMessageType.Call, seqid_));
      keepAlive_args args = new keepAlive_args();
      args.Session = Session;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public void recv_keepAlive()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      keepAlive_result result = new keepAlive_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.ex) {
        throw result.Ex;
      }
      return;
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_inputPasswd(AsyncCallback callback, object state, string Session, int iLockType, string strPassword)
    {
      return send_inputPasswd(callback, state, Session, iLockType, strPassword);
    }

    public void End_inputPasswd(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      recv_inputPasswd();
    }

    #endif

    /// <summary>
    /// 输入密码
    /// </summary>
    /// <param name="Session">用户Session</param>
    /// <param name="iLockType">锁类型</param>
    /// <param name="strPassword">密码</param>
    public void inputPasswd(string Session, int iLockType, string strPassword)
    {
      #if !SILVERLIGHT
      send_inputPasswd(Session, iLockType, strPassword);
      recv_inputPasswd();

      #else
      var asyncResult = Begin_inputPasswd(null, null, Session, iLockType, strPassword);
      End_inputPasswd(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_inputPasswd(AsyncCallback callback, object state, string Session, int iLockType, string strPassword)
    #else
    public void send_inputPasswd(string Session, int iLockType, string strPassword)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("inputPasswd", TMessageType.Call, seqid_));
      inputPasswd_args args = new inputPasswd_args();
      args.Session = Session;
      args.ILockType = iLockType;
      args.StrPassword = strPassword;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public void recv_inputPasswd()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      inputPasswd_result result = new inputPasswd_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.ex) {
        throw result.Ex;
      }
      return;
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_ResetPasswd(AsyncCallback callback, object state, string strDevCode, int iLockType, string strPassword)
    {
      return send_ResetPasswd(callback, state, strDevCode, iLockType, strPassword);
    }

    public void End_ResetPasswd(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      recv_ResetPasswd();
    }

    #endif

    /// <summary>
    /// 重置密码
    /// </summary>
    /// <param name="strDevCode">加密后的设备编码：使得只有某些指定设备才可以进行重置密码，防止黑客通过抓包得到接口并直接调用接口</param>
    /// <param name="iLockType">锁类型</param>
    /// <param name="strPassword">密码</param>
    public void ResetPasswd(string strDevCode, int iLockType, string strPassword)
    {
      #if !SILVERLIGHT
      send_ResetPasswd(strDevCode, iLockType, strPassword);
      recv_ResetPasswd();

      #else
      var asyncResult = Begin_ResetPasswd(null, null, strDevCode, iLockType, strPassword);
      End_ResetPasswd(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_ResetPasswd(AsyncCallback callback, object state, string strDevCode, int iLockType, string strPassword)
    #else
    public void send_ResetPasswd(string strDevCode, int iLockType, string strPassword)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("ResetPasswd", TMessageType.Call, seqid_));
      ResetPasswd_args args = new ResetPasswd_args();
      args.StrDevCode = strDevCode;
      args.ILockType = iLockType;
      args.StrPassword = strPassword;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public void recv_ResetPasswd()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      ResetPasswd_result result = new ResetPasswd_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.ex) {
        throw result.Ex;
      }
      return;
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_modifyPasswd(AsyncCallback callback, object state, string strOldPasswd, string strNewPasswd, int iLockType)
    {
      return send_modifyPasswd(callback, state, strOldPasswd, strNewPasswd, iLockType);
    }

    public void End_modifyPasswd(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      recv_modifyPasswd();
    }

    #endif

    /// <summary>
    /// 修改密码
    /// </summary>
    /// <param name="strOldPasswd"></param>
    /// <param name="strNewPasswd"></param>
    /// <param name="iLockType">锁类型</param>
    public void modifyPasswd(string strOldPasswd, string strNewPasswd, int iLockType)
    {
      #if !SILVERLIGHT
      send_modifyPasswd(strOldPasswd, strNewPasswd, iLockType);
      recv_modifyPasswd();

      #else
      var asyncResult = Begin_modifyPasswd(null, null, strOldPasswd, strNewPasswd, iLockType);
      End_modifyPasswd(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_modifyPasswd(AsyncCallback callback, object state, string strOldPasswd, string strNewPasswd, int iLockType)
    #else
    public void send_modifyPasswd(string strOldPasswd, string strNewPasswd, int iLockType)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("modifyPasswd", TMessageType.Call, seqid_));
      modifyPasswd_args args = new modifyPasswd_args();
      args.StrOldPasswd = strOldPasswd;
      args.StrNewPasswd = strNewPasswd;
      args.ILockType = iLockType;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public void recv_modifyPasswd()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      modifyPasswd_result result = new modifyPasswd_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.ex) {
        throw result.Ex;
      }
      return;
    }

  }
  public class Processor : TProcessor {
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_["connectServer"] = connectServer_Process;
      processMap_["disconnectServer"] = disconnectServer_Process;
      processMap_["keepAlive"] = keepAlive_Process;
      processMap_["inputPasswd"] = inputPasswd_Process;
      processMap_["ResetPasswd"] = ResetPasswd_Process;
      processMap_["modifyPasswd"] = modifyPasswd_Process;
    }

    protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
    private Iface iface_;
    protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

    public bool Process(TProtocol iprot, TProtocol oprot)
    {
      try
      {
        TMessage msg = iprot.ReadMessageBegin();
        ProcessFunction fn;
        processMap_.TryGetValue(msg.Name, out fn);
        if (fn == null) {
          TProtocolUtil.Skip(iprot, TType.Struct);
          iprot.ReadMessageEnd();
          TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
          oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
          x.Write(oprot);
          oprot.WriteMessageEnd();
          oprot.Transport.Flush();
          return true;
        }
        fn(msg.SeqID, iprot, oprot);
      }
      catch (IOException)
      {
        return false;
      }
      return true;
    }

    public void connectServer_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      connectServer_args args = new connectServer_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      connectServer_result result = new connectServer_result();
      try {
        result.Success = iface_.connectServer(args.StrDevCode);
      } catch (AirException ex) {
        result.Ex = ex;
      }
      oprot.WriteMessageBegin(new TMessage("connectServer", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void disconnectServer_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      disconnectServer_args args = new disconnectServer_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      disconnectServer_result result = new disconnectServer_result();
      try {
        iface_.disconnectServer(args.Session);
      } catch (AirException ex) {
        result.Ex = ex;
      }
      oprot.WriteMessageBegin(new TMessage("disconnectServer", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void keepAlive_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      keepAlive_args args = new keepAlive_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      keepAlive_result result = new keepAlive_result();
      try {
        iface_.keepAlive(args.Session);
      } catch (AirException ex) {
        result.Ex = ex;
      }
      oprot.WriteMessageBegin(new TMessage("keepAlive", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void inputPasswd_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      inputPasswd_args args = new inputPasswd_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      inputPasswd_result result = new inputPasswd_result();
      try {
        iface_.inputPasswd(args.Session, args.ILockType, args.StrPassword);
      } catch (AirException ex) {
        result.Ex = ex;
      }
      oprot.WriteMessageBegin(new TMessage("inputPasswd", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void ResetPasswd_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      ResetPasswd_args args = new ResetPasswd_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      ResetPasswd_result result = new ResetPasswd_result();
      try {
        iface_.ResetPasswd(args.StrDevCode, args.ILockType, args.StrPassword);
      } catch (AirException ex) {
        result.Ex = ex;
      }
      oprot.WriteMessageBegin(new TMessage("ResetPasswd", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void modifyPasswd_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      modifyPasswd_args args = new modifyPasswd_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      modifyPasswd_result result = new modifyPasswd_result();
      try {
        iface_.modifyPasswd(args.StrOldPasswd, args.StrNewPasswd, args.ILockType);
      } catch (AirException ex) {
        result.Ex = ex;
      }
      oprot.WriteMessageBegin(new TMessage("modifyPasswd", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class connectServer_args : TBase
  {
    private string _strDevCode;

    /// <summary>
    /// 设备编码(加密)
    /// </summary>
    public string StrDevCode
    {
      get
      {
        return _strDevCode;
      }
      set
      {
        __isset.strDevCode = true;
        this._strDevCode = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool strDevCode;
    }

    public connectServer_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              StrDevCode = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("connectServer_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (StrDevCode != null && __isset.strDevCode) {
        field.Name = "strDevCode";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(StrDevCode);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("connectServer_args(");
      sb.Append("StrDevCode: ");
      sb.Append(StrDevCode);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class connectServer_result : TBase
  {
    private string _success;
    private AirException _ex;

    public string Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }

    /// <summary>
    /// 抛出异常
    /// </summary>
    public AirException Ex
    {
      get
      {
        return _ex;
      }
      set
      {
        __isset.ex = true;
        this._ex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
      public bool ex;
    }

    public connectServer_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 0:
            if (field.Type == TType.String) {
              Success = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 1:
            if (field.Type == TType.Struct) {
              Ex = new AirException();
              Ex.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("connectServer_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.success) {
        if (Success != null) {
          field.Name = "Success";
          field.Type = TType.String;
          field.ID = 0;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Success);
          oprot.WriteFieldEnd();
        }
      } else if (this.__isset.ex) {
        if (Ex != null) {
          field.Name = "Ex";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Ex.Write(oprot);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("connectServer_result(");
      sb.Append("Success: ");
      sb.Append(Success);
      sb.Append(",Ex: ");
      sb.Append(Ex== null ? "<null>" : Ex.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class disconnectServer_args : TBase
  {
    private string _Session;

    /// <summary>
    /// 用户Session
    /// </summary>
    public string Session
    {
      get
      {
        return _Session;
      }
      set
      {
        __isset.Session = true;
        this._Session = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Session;
    }

    public disconnectServer_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Session = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("disconnectServer_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Session != null && __isset.Session) {
        field.Name = "Session";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Session);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("disconnectServer_args(");
      sb.Append("Session: ");
      sb.Append(Session);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class disconnectServer_result : TBase
  {
    private AirException _ex;

    /// <summary>
    /// 抛出异常
    /// </summary>
    public AirException Ex
    {
      get
      {
        return _ex;
      }
      set
      {
        __isset.ex = true;
        this._ex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ex;
    }

    public disconnectServer_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Ex = new AirException();
              Ex.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("disconnectServer_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.ex) {
        if (Ex != null) {
          field.Name = "Ex";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Ex.Write(oprot);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("disconnectServer_result(");
      sb.Append("Ex: ");
      sb.Append(Ex== null ? "<null>" : Ex.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class keepAlive_args : TBase
  {
    private string _Session;

    /// <summary>
    /// 用户Session
    /// </summary>
    public string Session
    {
      get
      {
        return _Session;
      }
      set
      {
        __isset.Session = true;
        this._Session = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Session;
    }

    public keepAlive_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Session = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("keepAlive_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Session != null && __isset.Session) {
        field.Name = "Session";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Session);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("keepAlive_args(");
      sb.Append("Session: ");
      sb.Append(Session);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class keepAlive_result : TBase
  {
    private AirException _ex;

    /// <summary>
    /// 抛出异常
    /// </summary>
    public AirException Ex
    {
      get
      {
        return _ex;
      }
      set
      {
        __isset.ex = true;
        this._ex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ex;
    }

    public keepAlive_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Ex = new AirException();
              Ex.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("keepAlive_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.ex) {
        if (Ex != null) {
          field.Name = "Ex";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Ex.Write(oprot);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("keepAlive_result(");
      sb.Append("Ex: ");
      sb.Append(Ex== null ? "<null>" : Ex.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class inputPasswd_args : TBase
  {
    private string _Session;
    private int _iLockType;
    private string _strPassword;

    /// <summary>
    /// 用户Session
    /// </summary>
    public string Session
    {
      get
      {
        return _Session;
      }
      set
      {
        __isset.Session = true;
        this._Session = value;
      }
    }

    /// <summary>
    /// 锁类型
    /// </summary>
    public int ILockType
    {
      get
      {
        return _iLockType;
      }
      set
      {
        __isset.iLockType = true;
        this._iLockType = value;
      }
    }

    /// <summary>
    /// 密码
    /// </summary>
    public string StrPassword
    {
      get
      {
        return _strPassword;
      }
      set
      {
        __isset.strPassword = true;
        this._strPassword = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Session;
      public bool iLockType;
      public bool strPassword;
    }

    public inputPasswd_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Session = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              ILockType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              StrPassword = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("inputPasswd_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Session != null && __isset.Session) {
        field.Name = "Session";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Session);
        oprot.WriteFieldEnd();
      }
      if (__isset.iLockType) {
        field.Name = "iLockType";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ILockType);
        oprot.WriteFieldEnd();
      }
      if (StrPassword != null && __isset.strPassword) {
        field.Name = "strPassword";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(StrPassword);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("inputPasswd_args(");
      sb.Append("Session: ");
      sb.Append(Session);
      sb.Append(",ILockType: ");
      sb.Append(ILockType);
      sb.Append(",StrPassword: ");
      sb.Append(StrPassword);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class inputPasswd_result : TBase
  {
    private AirException _ex;

    /// <summary>
    /// 抛出异常
    /// </summary>
    public AirException Ex
    {
      get
      {
        return _ex;
      }
      set
      {
        __isset.ex = true;
        this._ex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ex;
    }

    public inputPasswd_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Ex = new AirException();
              Ex.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("inputPasswd_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.ex) {
        if (Ex != null) {
          field.Name = "Ex";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Ex.Write(oprot);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("inputPasswd_result(");
      sb.Append("Ex: ");
      sb.Append(Ex== null ? "<null>" : Ex.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ResetPasswd_args : TBase
  {
    private string _strDevCode;
    private int _iLockType;
    private string _strPassword;

    /// <summary>
    /// 加密后的设备编码：使得只有某些指定设备才可以进行重置密码，防止黑客通过抓包得到接口并直接调用接口
    /// </summary>
    public string StrDevCode
    {
      get
      {
        return _strDevCode;
      }
      set
      {
        __isset.strDevCode = true;
        this._strDevCode = value;
      }
    }

    /// <summary>
    /// 锁类型
    /// </summary>
    public int ILockType
    {
      get
      {
        return _iLockType;
      }
      set
      {
        __isset.iLockType = true;
        this._iLockType = value;
      }
    }

    /// <summary>
    /// 密码
    /// </summary>
    public string StrPassword
    {
      get
      {
        return _strPassword;
      }
      set
      {
        __isset.strPassword = true;
        this._strPassword = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool strDevCode;
      public bool iLockType;
      public bool strPassword;
    }

    public ResetPasswd_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              StrDevCode = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              ILockType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              StrPassword = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ResetPasswd_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (StrDevCode != null && __isset.strDevCode) {
        field.Name = "strDevCode";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(StrDevCode);
        oprot.WriteFieldEnd();
      }
      if (__isset.iLockType) {
        field.Name = "iLockType";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ILockType);
        oprot.WriteFieldEnd();
      }
      if (StrPassword != null && __isset.strPassword) {
        field.Name = "strPassword";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(StrPassword);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ResetPasswd_args(");
      sb.Append("StrDevCode: ");
      sb.Append(StrDevCode);
      sb.Append(",ILockType: ");
      sb.Append(ILockType);
      sb.Append(",StrPassword: ");
      sb.Append(StrPassword);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ResetPasswd_result : TBase
  {
    private AirException _ex;

    /// <summary>
    /// 抛出异常
    /// </summary>
    public AirException Ex
    {
      get
      {
        return _ex;
      }
      set
      {
        __isset.ex = true;
        this._ex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ex;
    }

    public ResetPasswd_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Ex = new AirException();
              Ex.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ResetPasswd_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.ex) {
        if (Ex != null) {
          field.Name = "Ex";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Ex.Write(oprot);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ResetPasswd_result(");
      sb.Append("Ex: ");
      sb.Append(Ex== null ? "<null>" : Ex.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class modifyPasswd_args : TBase
  {
    private string _strOldPasswd;
    private string _strNewPasswd;
    private int _iLockType;

    public string StrOldPasswd
    {
      get
      {
        return _strOldPasswd;
      }
      set
      {
        __isset.strOldPasswd = true;
        this._strOldPasswd = value;
      }
    }

    public string StrNewPasswd
    {
      get
      {
        return _strNewPasswd;
      }
      set
      {
        __isset.strNewPasswd = true;
        this._strNewPasswd = value;
      }
    }

    /// <summary>
    /// 锁类型
    /// </summary>
    public int ILockType
    {
      get
      {
        return _iLockType;
      }
      set
      {
        __isset.iLockType = true;
        this._iLockType = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool strOldPasswd;
      public bool strNewPasswd;
      public bool iLockType;
    }

    public modifyPasswd_args() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              StrOldPasswd = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              StrNewPasswd = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              ILockType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("modifyPasswd_args");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (StrOldPasswd != null && __isset.strOldPasswd) {
        field.Name = "strOldPasswd";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(StrOldPasswd);
        oprot.WriteFieldEnd();
      }
      if (StrNewPasswd != null && __isset.strNewPasswd) {
        field.Name = "strNewPasswd";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(StrNewPasswd);
        oprot.WriteFieldEnd();
      }
      if (__isset.iLockType) {
        field.Name = "iLockType";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ILockType);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("modifyPasswd_args(");
      sb.Append("StrOldPasswd: ");
      sb.Append(StrOldPasswd);
      sb.Append(",StrNewPasswd: ");
      sb.Append(StrNewPasswd);
      sb.Append(",ILockType: ");
      sb.Append(ILockType);
      sb.Append(")");
      return sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class modifyPasswd_result : TBase
  {
    private AirException _ex;

    /// <summary>
    /// 抛出异常
    /// </summary>
    public AirException Ex
    {
      get
      {
        return _ex;
      }
      set
      {
        __isset.ex = true;
        this._ex = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ex;
    }

    public modifyPasswd_result() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Ex = new AirException();
              Ex.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("modifyPasswd_result");
      oprot.WriteStructBegin(struc);
      TField field = new TField();

      if (this.__isset.ex) {
        if (Ex != null) {
          field.Name = "Ex";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Ex.Write(oprot);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("modifyPasswd_result(");
      sb.Append("Ex: ");
      sb.Append(Ex== null ? "<null>" : Ex.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
